services:
  db:
    image: postgres:15
    container_name: uniface_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Bazada ham vaqt to'g'ri bo'lishi uchun
      TZ: Asia/Tashkent
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: uniface_api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://uniface_db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY: ${MY_AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${MY_AWS_SECRET_KEY}
      JWT_SECRET: ${MY_JWT_SECRET}
      # --- TimeFold ------
      TIMEFOLD_SOLVER_PLANNING_SOLUTION_CLASS: com.uniface.matrix.domain.Timetable
      # --- VAQT ZONASINI SOZLASH ---
      TZ: Asia/Tashkent
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Tashkent"
      # -----------------------------
    depends_on:
      - db