spring:
  application:
    name: UniFace

  datasource:
    # Docker ichida SPRING_DATASOURCE_URL environment ishlatganing uchun
    # bu yerda ularni yozmasang ham bo'ladi, lekin Timefold uchun quyidagilar kerak:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

timefold:
  solver:
    termination:
      # 'best-score-feasible: true' degan joyini o'chirib tashla
      # O'rniga faqat vaqt yoki ball limitini qo'yish kerak:
      spent-limit: 1m # Hisoblash uchun maksimal 30 soniya vaqt beradi