spring.application.name=UniFace
server.port=8081

# AWS Sozlamalari (Docker-compose orqali keladi)

#======================================================================
 # Haqiqiy ma'lumotlar
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
jwt.secret=${JWT_SECRET}
aws.region=us-east-1

# PostgreSQL (Docker network ichida 'uniface_db' deb chaqiramiz)
# Bu yerda o'zgaruvchilarni Docker-compose'dan olishi uchun shunday qoldiramiz:
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#======================================================================
# JPA/Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Rasmlar uchun limitni 10MB gacha oshiramiz
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
