spring.application.name=UniFace

# AWS Sozlamalari (O'zingnikini qo'y)
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=us-east-1
server.port=8081

# PostgreSQL (Agar o'rnatilgan bo'lsa)
spring.datasource.url=jdbc:postgresql://localhost:5432/uniface_db
spring.datasource.username=postgres
spring.datasource.password=password // o'zingni parolingni yoz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true