name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/UniFace || { echo "Papka topilmadi!"; exit 1; }
            
            echo "📥 Kod yangilanmoqda..."
            git pull origin master
            
            echo "🏗️ Serverda build jarayoni boshlandi..."
            chmod +x gradlew
            ./gradlew build -x test
            
            echo "🛑 Konteynerlar qayta yuklanmoqda..."
            docker-compose down
            docker-compose up --build -d
            
            echo "🧹 Tozalash..."
            docker image prune -f
            echo "✅ Hammasi muvaffaqiyatli yakunlandi!"
            docker image prune -f
